### ISSUE TITLE
Add a way to cancel projectiles getting stuck

### ISSUE THREAD

**Issue by christian162** [Bloepiloepi/MinestomPvP#6]
[https://www.youtube.com/watch?v=o001X4xabg4](url)

**Comment by Bloepiloepi** [comment]
This is in fact an issue with Minestom (every block is treated as a full block when colliding with them) which I can’t easily fix. Other entities have this problem as well. Implementing block shapes into this extension would be difficult and goes too far in my opinion, I am sorry.

In the future I might add a way to cancel projectiles being stuck so you can implement block shapes yourself, so I will leave this issue open

**Comment by CatDevz** [comment]
Is arrow collision handled here?
https://github.com/Bloepiloepi/MinestomPvP/blob/4685dce6e3753a5c840646d9c01ae593796ecc17/src/main/java/io/github/bloepiloepi/pvp/projectile/CustomEntityProjectile.java#L213-L216
If it is handled there, than wouldn't it be possible to get the block shapes from Minestom ([here](https://github.com/Minestom/MinestomDataGenerator/blob/master/DataGenerator/src/main/java/net/minestom/generators/BlockGenerator.java#L131-L136)) and take that into account. If you're writing your own collision code I feel like that would be within the scope of this extension.

**Comment by Bloepiloepi** [comment]
There is currently no easy way to parse or use the block shapes, Minestom does not have an api for it. Once it does, it will likely be implemented in Minestoms collisions and I will use it here, too

**Comment by Bloepiloepi** [comment]
The original issue in the video has been fixed! I decided to not make `ProjectileBlockHitEvent` cancellable, because it is difficult to implement correctly. I still might do it later
